#!/bin/sh
#
# router        Starts NAT router.
#

umask 077

reset() {
# delete all firewall rolss
	iptables -F
	iptables -X
	iptables -t nat -F
	iptables -t nat -X
#	iptables -t mangle -F
#	iptables -t mangle -X
#	iptables -P INPUT ACCEPT
	iptables -P FORWARD ACCEPT
#	iptables -P OUTPUT ACCEPT
}
start() {
	printf "Starting NAT: "
	reset
	echo 1 > /proc/sys/net/ipv4/ip_forward
	iptables -t nat -A POSTROUTING -o wwan0 -j MASQUERADE
	iptables -A FORWARD -i wwan0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
	iptables -A FORWARD -i wlan0 -o wwan0 -j ACCEPT
	echo "OK"
}
stop() {
	printf "Stopping NAT: "
	echo 0 > /proc/sys/net/ipv4/ip_forward
	reset
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
